apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami-labs/sealed-secrets/
    path: helm/sealed-secrets
    targetRevision: v0.15.0
    helm:
      releaseName: sealed-secrets-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
